version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  flower:
    container_name: flower
    image: mher/flower
    command: celery -A weather.tasks flower
    ports:
      - "5555:5555"
    entrypoint: "celery -b redis://redis:6379 flower"
    environment:
      - FLOWER_BROKER=redis://redis:6379/0 # Change this to your Celery broker configuration
